---
title: "Booth WMAN 633 Semeter Project"
author: "Ian Taylor Booth"
output: html_document
---

```{r, echo = FALSE}
#Import Project data
data <-read.csv('CRData3.csv')
groupmort <- read.csv('Groupmort.csv')
head(data)
head(groupmort)

#Alter data for analyses
data$RAMP <- factor(data$RAMP) 
data$HookLocation[data$HookLocation=="E"] <- "G"
```

```{r, echo = FALSE}
### Load relevant packages
library(ggplot2)
library(dplyr)
library(AICcmodavg)
library(ggpubr)
library(sjPlot)
```


```{r, echo = FALSE}
### Build Candidate Models for AIC 
TempModel <- glm(y ~ Temp, family = binomial, data = data)
summary(TempModel)

FightModel <- glm(y ~ FightTime, family = binomial, data = data)
summary(FightModel)

Fight2 <- glm(y ~ Temp * FightTime, family = binomial, data = data)

Fight3 <- glm(y ~ Temp + FightTime, family = binomial, data = data)

HandlingModel <- glm(y ~ NetTime, family = binomial, data = data)

Handling2 <- glm(y ~ Temp * NetTime, family = binomial, data = data)

Handling3 <- glm(y ~ Temp + NetTime, family = binomial, data = data)

Total <- glm(y ~ TotalTime, family = binomial, data = data)

Total2 <- glm(y ~ TotalTime + Temp, family = binomial, data = data)

Total3 <- glm(y ~ TotalTime * Temp, family = binomial, data = data)
summary(Total3)

SizeModel <- glm(y ~ Length + Weight, family = binomial, data = data)

AgeModel <- glm(y ~ Age, family = binomial, data = data)

SexModel <- glm(y ~ Sex, family = binomial, data = data)

FightNet <- glm(y ~ Temp * NetTime + FightTime, family = binomial, data = data)

FightNet2 <- glm(y ~ Temp * FightTime + NetTime, family = binomial, data = data)

HookLocation <- glm(y ~ HookLocation, family = binomial, data = data)

Hook <- glm(y ~ Temp + HookLocation, family = binomial, data = data)

Hook2 <- glm(y ~ Temp * HookLocation, family = binomial, data = data)

Hook3 <- glm(y ~ TotalTime + HookLocation, family = binomial, data = data)

Hook4 <- glm(y ~ TotalTime * HookLocation, family = binomial, data = data)

Combine <- glm(y ~ Temp * TotalTime + HookLocation, family = binomial, data = data)

Combine2 <- glm(y ~ Temp * HookLocation + TotalTime, family = binomial, data = data)

Exp <- glm(y ~ Temp * FightTime * NetTime, family = binomial, data = data)

Exp2 <- glm(y ~ Temp * TotalTime * HookLocation, family = binomial, data = data)
```


```{r, echo = FALSE}
#Model Selection Using AIC
AICc(mod = TempModel, second.ord = F)

cand.set <-list(
  M1 = TempModel, M2 = FightModel, M3 = Fight2, M4 = Fight3, M5 = HandlingModel, 
  M6 = Handling2, M7 = Handling3, M8 = Total, M9 = Total2, M10 = Total3, M11 = SizeModel,
  M12 = SexModel, M13 = AgeModel, M14 = FightNet2, M15 = FightNet, M16 = HookLocation, M17 = Hook,
  M18 = Hook2, M19 = Combine, M20 = Combine2, M21 = Hook3, M22 = Hook4, M23 = Exp, M24 = Exp2
)

#AIC Comparison Table
mods <- aictab(cand.set = cand.set, second.ord = F)
mods

##Top Model

fit <- glm(y ~ Temp * TotalTime, family = binomial, data = data)
summary(fit)
```


```{r, echo = FALSE}
##Creat Box Plot showing differences in temps between fish that died and fish that survived
#compute mean and SD by groups 
group_by(data, StatusType) %>%
  summarise(
    count = n(),
    mean = mean(Temp, na.rm = TRUE),
    sd = sd(Temp, na.rm = TRUE)
  )
### plot
ggline(data, x = "StatusType", y = "Temp", xlab = FALSE, ylab = "Temperature (Celsius)",
       add = c("mean_ci", "boxplot")
)
```


```{r, echo = FALSE}
#group into experimental and control groups, get summary statistics
group_by(groupmort, group) %>%
  summarise(
    count = n(),
    mean = mean(ï..y, na.rm = TRUE),
    sd = sd(ï..y, na.rm = TRUE)
  )
## compare independent means of mortality rates between experimental and control groups
anovatest3 <- aov(ï..y ~ group, data = groupmort)
summary(anovatest3)
```


```{r, echo = FALSE}
##### Assessing Effectiveness of Hook Location to predict mortality
anovatest <- aov(y ~ HookLocation, data = data)
summary(anovatest)
tukey.test <- TukeyHSD(anovatest)
tukey.test
```


```{r, echo = FALSE}
#Assessing RAMP as a mortality predictor
anovaRAMP <- aov(y ~ RAMP, data = data)
summary(anovaRAMP)
#Compare independent means of catch temperature between dead fish and alive fish
anovatemp <- aov(Temp ~ StatusType, data = data)
summary(anovatemp)
# compare independent means of total time between dead fish and alive fish
anovatest2 <- aov(TotalTime ~ StatusType, data = data)
summary(anovatest2)
```


```{r, echo = FALSE}
#### Plot effect of Total Time on log odds ratio when Temperature is fixed at its mean

df <- data.frame(
  TotalTime = seq(min(data$TotalTime), max(data$TotalTime), length.out = 100),
  Temp = mean(data$Temp)
  )

prd <-predict.glm(object = fit, newdata = df, se.fit = T)
lower <- plogis(prd$fit - qnorm(0.975) * prd$se.fit)
upper <- plogis(prd$fit + qnorm(0.975) * prd$se.fit)

y <- plogis(prd$fit)
x <- df$TotalTime

plot(y = y, x = x, xlab = 'Angling Duration (sec)', ylab = 'Log Odds Ratio', 
     cex.axis = 1.5, cex.lab = 1.5, ylim = c(min(lower), max(upper)))
lines(x = df$TotalTime, y = lower, lty = 2)
lines(x = df$TotalTime, y = upper, lty = 2)
```


```{r, echo = FALSE}
#### Plot effect of Temperature on log odds ratio when Total Time is fixed at its mean
df2 <- data.frame(
  Temp = seq(min(data$Temp), max(data$Temp), length.out = 100),
  TotalTime = mean(data$TotalTime)
  )

prd2 <-predict.glm(object = fit, newdata = df2, se.fit = T)
lower2 <- plogis(prd2$fit - qnorm(0.975) * prd2$se.fit)
upper2 <- plogis(prd2$fit + qnorm(0.975) * prd2$se.fit)

y2 <- plogis(prd2$fit)
x2 <- df2$Temp

plot(y = y2, x = x2, xlab = 'Temperature (Celsius)', ylab = 'Log Odds Ratio',
     cex.axis = 1.5, cex.lab = 1.5, ylim = c(0, 1))
lines(x = df2$Temp, y = lower2, lty = 2)
lines(x = df2$Temp, y = upper2, lty = 2)
```


```{r, echo = FALSE}
##### Plot Probability of Mortality over a range of time when temperature is fixed at its quartiles (25.87, 27.8, 29.72)
fit3 <- glm(y ~ TotalTime * Temp, family = binomial, data = data)

 plot_model(fit3, type = "int", mdrt.values = "all", axis.title = "Motality", ci.lvl = .95,
            title = "Predicted Prob. of Mortality", legend.title = "Temp (Cesius)")

```

``` {r, echo = FALSE}
 #### Plot prob. of mortality over a range of temps when time is fixed at its quartiles (137.2, 180.3, 223.3) 
 plot_model(fit, type = "int", mdrt.values = "all", axis.title = "Mortality", ci.lvl = .95,
            title = "Predicted Prob. of Mortality")
```

```{r, echo = FALSE}
#Summary staistics table for fitted model
tab_model(Total3, p.style = "numeric_stars", show.ci = 0.95, transform = NULL)
summary(Total3)
```
